





import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import OfflineBanner from "@/components/OfflineBanner";
import MobileNav from "@/components/MobileNav";
import PageAnimations from "@/components/PageAnimations";
import PWAInstallButton from "@/components/PWAInstallButton";
import "./globals.css";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PATANAFUU",
  description: "Generated by PULSAR",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "PATANAFUU",
  },
  formatDetection: {
    telephone: false,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  themeColor: "#10b981",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <head>
          <link rel="manifest" href="/manifest.json" />
          <link rel="apple-touch-icon" href="/icon-192x192.png" />
        </head>
        <body className="min-h-full flex flex-col">
          <PageAnimations />
          <OfflineBanner />
          <header className="relative z-10 bg-gray-900 border-b border-gray-800">
            <div className="mx-auto max-w-6xl px-4 py-4 sm:px-6 flex items-center justify-between">
              <Link href="/" className="flex items-center">
                <Image 
                  src="/Creative Idea.svg" 
                  alt="PATANAFUU Logo" 
                  width={150} 
                  height={50}
                  className="h-8 w-auto sm:h-10"
                />
              </Link>
              <MobileNav />
            </div>
          </header>
          <PWAInstallButton />
          {children}
          <footer className="relative z-10 bg-gray-800 text-slate-300 py-8 mt-auto">
            <div className="mx-auto max-w-6xl px-4 sm:px-6">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                <div>
                  <div className="mb-4">
                    <Image 
                      src="/Creative Idea.svg" 
                      alt="PATANAFUU Logo" 
                      width={150} 
                      height={50}
                      className="h-10 w-auto sm:h-12"
                    />
                  </div>
                  <p className="text-xs sm:text-sm">Your trusted platform for connecting with verified service providers across Kenya.</p>
                </div>
                <div>
                  <h3 className="text-base font-semibold text-white mb-4 sm:text-lg">Quick Links</h3>
                  <ul className="space-y-2 text-xs sm:text-sm">
                    <li><Link href="/services" className="hover:text-emerald-400 transition">Find Services</Link></li>
                    <li><Link href="/providers/apply" className="hover:text-emerald-400 transition">Become a Provider</Link></li>
                    <li><Link href="/admin/bookings" className="hover:text-emerald-400 transition">Admin Dashboard</Link></li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-base font-semibold text-white mb-4 sm:text-lg">Legal</h3>
                  <ul className="space-y-2 text-xs sm:text-sm">
                    <li><Link href="/privacy" className="hover:text-emerald-400 transition">Privacy Policy</Link></li>
                    <li><Link href="/refund" className="hover:text-emerald-400 transition">Refund Policy</Link></li>
                    <li><Link href="/terms" className="hover:text-emerald-400 transition">Terms of Service</Link></li>
                  </ul>
                </div>
              </div>
              <div className="border-t border-gray-700 mt-8 pt-6 text-center text-xs sm:text-sm">
                <p>&copy; {new Date().getFullYear()} PATANAFUU. All rights reserved.</p>
                <p className="mt-2 text-slate-400">Contact: stilespulsar77@gmail.com</p>
              </div>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
